from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel
from datetime import datetime
import os
import uuid

from docx import Document
from pptx import Presentation
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPORT_DIR = os.path.join(BASE_DIR, "reports")
os.makedirs(REPORT_DIR, exist_ok=True)

# -----------------------------
# REQUEST MODEL
# -----------------------------
class ReportRequest(BaseModel):
    companyName: str
    reportType: str
    insights: list[str]


# -----------------------------
# PDF GENERATOR (SAFE)
# -----------------------------
def generate_pdf(data: ReportRequest, filepath: str):
    c = canvas.Canvas(filepath, pagesize=A4)
    width, height = A4

    # COVER PAGE
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width / 2, height - 120, data.companyName)

    c.setFont("Helvetica", 16)
    c.drawCentredString(
        width / 2, height - 160, f"{data.reportType} Energy Report"
    )

    c.setFont("Helvetica", 12)
    c.drawCentredString(
        width / 2, height - 200,
        f"Generated on {datetime.now().strftime('%d %b %Y')}"
    )

    c.drawCentredString(width / 2, 40, "Generated by InsightFlow")
    c.showPage()

    # CONTENT PAGES (2 INSIGHTS PER PAGE)
    for i in range(0, len(data.insights), 2):
        y = height - 80

        for j in range(2):
            if i + j >= len(data.insights):
                break

            # Graph placeholder
            c.rect(60, y - 100, width - 120, 60)
            c.drawString(70, y - 120, "Graph Placeholder")

            # Insight
            text = c.beginText(70, y - 150)
            text.setFont("Helvetica", 11)
            text.textLines(data.insights[i + j])
            c.drawText(text)

            y -= 240

        c.drawCentredString(width / 2, 40, "Generated by InsightFlow")
        c.showPage()

    c.save()


# -----------------------------
# WORD GENERATOR (SAFE)
# -----------------------------
def generate_word(data: ReportRequest, path: str):
    doc = Document()

    doc.add_heading(data.companyName, level=1)
    doc.add_heading(f"{data.reportType} Energy Report", level=2)
    doc.add_paragraph(f"Generated on: {datetime.now().strftime('%d %b %Y')}")
    doc.add_page_break()

    for i, insight in enumerate(data.insights):
        doc.add_paragraph("Graph Placeholder", style="Intense Quote")
        doc.add_paragraph(insight)

        if (i + 1) % 2 == 0:
            doc.add_page_break()

    doc.add_paragraph("Generated by InsightFlow")

    doc.save(path)



# -----------------------------
# PPT GENERATOR (SAFE)
# -----------------------------
def generate_ppt(data: ReportRequest, path: str):
    prs = Presentation()

    cover = prs.slides.add_slide(prs.slide_layouts[1])
    cover.shapes.title.text = data.companyName
    cover.placeholders[1].text = (
        f"{data.reportType} Energy Report\n"
        f"Generated on {datetime.now().strftime('%d %b %Y')}"
    )

    for insight in data.insights:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Energy Insight"
        slide.placeholders[1].text = f"Graph Placeholder\n\n{insight}"

    prs.save(path)



# -----------------------------
# DOWNLOAD ENDPOINT
# -----------------------------
@app.post("/download-report/{format}")
def download_report(format: str, data: ReportRequest):

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = data.companyName.replace(" ", "_")

    if format == "pdf":
        filename = f"{safe_name}_{data.reportType}_{timestamp}.pdf"
        filepath = os.path.join(REPORT_DIR, filename)
        generate_pdf(data, filepath)
        media_type = "application/pdf"

    elif format == "docx":
        filename = f"{safe_name}_{data.reportType}_{timestamp}.docx"
        filepath = os.path.join(REPORT_DIR, filename)
        generate_word(data, filepath)
        media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

    elif format == "pptx":
        filename = f"{safe_name}_{data.reportType}_{timestamp}.pptx"
        filepath = os.path.join(REPORT_DIR, filename)
        generate_ppt(data, filepath)
        media_type = "application/vnd.openxmlformats-officedocument.presentationml.presentation"

    else:
        return {"error": "Unsupported format"}

    return FileResponse(
        path=filepath,
        filename=filename,
        media_type=media_type,
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"'
        }
    )

